import { InvitationTemplate } from '../types'

export const custom_storybook_v1: InvitationTemplate = {
  id: 'custom-storybook',
  name: 'Custom Storybook',
  slug: 'custom-storybook',
  category: 'Traditional',
  style: 'Custom Illustrated',
  thumbnail: 'photo-1606800052052-a08af7148866',
  version: '1.0',
  status: 'published',
  price: 200000,
  badge: 'Custom',
  description: 'Your unique love story told through custom illustrations and animations.',
  keyFeatures: ['Custom Illustration Slots', 'Chapter-Style Storytelling', 'Animated Page Turns', 'RSVP & Guestbook'],
  experience: 'Every section reads like a page in your own storybook, with warm, hand-illustrated framing and gentle page-turn animation \u2014 built for couples who want something entirely their own.',
  theme: {
    colors: {
      primary: '#7A4B32',
      secondary: '#E8B95F',
      accent: '#E8734A',
      background: '#FFF8EE',
      text: '#3B2A1E',
      card: '#FFFDF8',
    },
    fonts: {
      heading: 'Fraunces',
      body: 'Nunito',
    },
    borderRadius: '16px',
  },
  sections: [
    {
      id: 'cover',
      type: 'cover',
      title: 'Cover',
      enabled: true,
      config: {
        groomName: 'Al Yafi',
        brideName: 'Yova',
        date: '10 Januari 2027',
        backgroundImage: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1200&auto=format',
      },
      elements: [],
      widgets: [],
      editableProperties: ['groomName', 'brideName', 'date', 'backgroundImage'],
    },
    {
      id: 'couple',
      type: 'couple',
      title: 'Mempelai',
      enabled: true,
      config: {
        groom: {
          name: 'Muhammad Al Yafi',
          parents: 'Putra dari Bapak Rizal & Ibu Mariana',
          image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format',
        },
        bride: {
          name: 'Yova Rahmadani',
          parents: 'Putri dari Bapak Hendra & Ibu Sari',
          image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format',
        },
      },
      elements: [],
      widgets: [],
      editableProperties: ['groom.name', 'groom.parents', 'groom.image', 'bride.name', 'bride.parents', 'bride.image'],
    },
    {
      id: 'event',
      type: 'event',
      title: 'Acara',
      enabled: true,
      config: {
        events: [
          {
            name: 'Akad Nikah',
            date: 'Minggu, 10 Jan 2027',
            time: '08:00 - 10:00 WIB',
            venue: 'Kediaman Mempelai Wanita',
            address: 'Jl. Sudirman No. 21, Lhokseumawe',
          },
          {
            name: 'Resepsi',
            date: 'Minggu, 10 Jan 2027',
            time: '11:00 - 15:00 WIB',
            venue: 'Balai Kota Lhokseumawe',
            address: 'Jl. Perdagangan No. 1, Lhokseumawe',
          },
        ],
      },
      elements: [],
      widgets: [
        { id: 'maps-akad', type: 'maps', config: { lat: 5.180, lng: 97.150 } },
      ],
      editableProperties: ['events'],
    },
    {
      id: 'story',
      type: 'story',
      title: 'Kisah Cinta',
      enabled: true,
      config: {
        stories: [
          { date: 'Bab 1 \u00b7 2018', title: 'Awal Mula', content: 'Dua orang asing yang dipertemukan lewat teman satu organisasi.' },
          { date: 'Bab 2 \u00b7 2022', title: 'Perjalanan', content: 'Melewati suka dan duka, saling menguatkan satu sama lain.' },
          { date: 'Bab 3 \u00b7 2027', title: 'Selamanya', content: 'Babak baru dimulai, menulis cerita bersama seumur hidup.' },
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['stories'],
    },
    {
      id: 'gallery',
      type: 'gallery',
      title: 'Galeri',
      enabled: true,
      config: {
        images: [
          'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&auto=format',
          'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&auto=format',
          'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format',
          'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format',
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['images'],
    },
    {
      id: 'gift',
      type: 'gift',
      title: 'Kado',
      enabled: true,
      config: {
        accounts: [
          { bank: 'BCA', number: '5123456789', name: 'Muhammad Al Yafi' },
        ],
        address: 'Jl. Sudirman No. 21, Lhokseumawe, Aceh',
      },
      elements: [],
      widgets: [],
      editableProperties: ['accounts', 'address'],
    },
    {
      id: 'rsvp',
      type: 'rsvp',
      title: 'RSVP',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
    {
      id: 'wishes',
      type: 'wishes',
      title: 'Ucapan',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
  ],
}
