import { InvitationTemplate } from '../types'

export const islamic_luxury_v1: InvitationTemplate = {
  id: 'islamic-luxury',
  name: 'Islamic Luxury',
  slug: 'islamic-luxury',
  category: 'Islamic',
  style: 'Islamic Luxury',
  thumbnail: 'photo-1583394293214-28ded15ee548',
  version: '1.0',
  status: 'published',
  price: 90000,
  description: 'Ornate Islamic patterns with interactive storytelling and smooth transitions.',
  keyFeatures: ['Islamic Ornament Motifs', 'Interactive Storytelling', 'Smooth Transitions', 'RSVP & Guestbook'],
  experience: 'This template pairs deep emerald and gold tones with ornate geometric patterns, telling your story through smooth, reveal-as-you-scroll transitions on any screen size.',
  theme: {
    colors: {
      primary: '#0B2A2E',
      secondary: '#C9A84C',
      accent: '#C9A84C',
      background: '#FAF7F0',
      text: '#1F1B16',
      card: '#FFFFFF',
    },
    fonts: {
      heading: 'Amiri',
      body: 'DM Sans',
    },
    borderRadius: '0px',
  },
  sections: [
    {
      id: 'cover',
      type: 'cover',
      title: 'Cover',
      enabled: true,
      config: {
        groomName: 'Al Yafi',
        brideName: 'Yova',
        date: '10 Januari 2027',
        backgroundImage: 'https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=1200&auto=format',
      },
      elements: [],
      widgets: [],
      editableProperties: ['groomName', 'brideName', 'date', 'backgroundImage'],
    },
    {
      id: 'couple',
      type: 'couple',
      title: 'Mempelai',
      enabled: true,
      config: {
        groom: {
          name: 'Muhammad Al Yafi',
          parents: 'Putra dari Bapak Rizal & Ibu Mariana',
          image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format',
        },
        bride: {
          name: 'Yova Rahmadani',
          parents: 'Putri dari Bapak Hendra & Ibu Sari',
          image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format',
        },
      },
      elements: [],
      widgets: [],
      editableProperties: ['groom.name', 'groom.parents', 'groom.image', 'bride.name', 'bride.parents', 'bride.image'],
    },
    {
      id: 'event',
      type: 'event',
      title: 'Acara',
      enabled: true,
      config: {
        events: [
          {
            name: 'Akad Nikah',
            date: 'Minggu, 10 Jan 2027',
            time: '08:00 - 10:00 WIB',
            venue: 'Masjid Raya Baiturrahman',
            address: 'Jl. Masjid Raya, Banda Aceh',
          },
          {
            name: 'Resepsi',
            date: 'Minggu, 10 Jan 2027',
            time: '11:00 - 16:00 WIB',
            venue: 'Hotel Hermes Palace',
            address: 'Jl. T. Nyak Arief, Banda Aceh',
          },
        ],
      },
      elements: [],
      widgets: [
        { id: 'maps-akad', type: 'maps', config: { lat: 5.553, lng: 95.317 } },
      ],
      editableProperties: ['events'],
    },
    {
      id: 'story',
      type: 'story',
      title: 'Kisah Cinta',
      enabled: true,
      config: {
        stories: [
          { date: '2020', title: 'Ta\u2019aruf', content: 'Perkenalan yang dijaga dalam kebaikan, diawali dengan niat yang lurus.' },
          { date: '2024', title: 'Khitbah', content: 'Lamaran sederhana penuh berkah, disaksikan oleh kedua keluarga.' },
          { date: '2027', title: 'Akad', content: 'Ijab kabul yang menyempurnakan separuh agama kami.' },
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['stories'],
    },
    {
      id: 'gallery',
      type: 'gallery',
      title: 'Galeri',
      enabled: true,
      config: {
        images: [
          'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&auto=format',
          'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format',
          'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&auto=format',
          'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&auto=format',
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['images'],
    },
    {
      id: 'gift',
      type: 'gift',
      title: 'Kado',
      enabled: true,
      config: {
        accounts: [
          { bank: 'BSI', number: '7123456789', name: 'Muhammad Al Yafi' },
          { bank: 'Bank Aceh Syariah', number: '0451234567', name: 'Yova Rahmadani' },
        ],
        address: 'Jl. Malikussaleh No. 5, Lhokseumawe, Aceh',
      },
      elements: [],
      widgets: [],
      editableProperties: ['accounts', 'address'],
    },
    {
      id: 'rsvp',
      type: 'rsvp',
      title: 'RSVP',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
    {
      id: 'wishes',
      type: 'wishes',
      title: 'Ucapan',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
  ],
}
