import { InvitationTemplate } from '../types'

export const minimal_white_v1: InvitationTemplate = {
  id: 'minimal-white',
  name: 'Minimal White',
  slug: 'minimal-white',
  category: 'Minimalist',
  style: 'Minimalist Modern',
  thumbnail: 'photo-1519741497674-611481863552',
  version: '1.0',
  status: 'published',
  price: 0,
  description: 'Elegant and clean design for a modern wedding celebration.',
  keyFeatures: ['Basic Customization', 'Responsive Design', 'RSVP Form'],
  experience: 'This template features free animations and transitions, perfectly optimized for both mobile and desktop viewing.',
  theme: {
    colors: {
      primary: '#FFFFFF',
      secondary: '#D9CFC2',
      accent: '#B08968',
      background: '#FDFCFA',
      text: '#2C2A28',
      card: '#FFFFFF',
    },
    fonts: {
      heading: 'Cormorant Garamond',
      body: 'Inter',
    },
    borderRadius: '2px',
  },
  sections: [
    {
      id: 'cover',
      type: 'cover',
      title: 'Cover',
      enabled: true,
      config: {
        groomName: 'Al Yafi',
        brideName: 'Yova',
        date: '10 Januari 2027',
        backgroundImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format',
      },
      elements: [],
      widgets: [],
      editableProperties: ['groomName', 'brideName', 'date', 'backgroundImage'],
    },
    {
      id: 'couple',
      type: 'couple',
      title: 'Mempelai',
      enabled: true,
      config: {
        groom: {
          name: 'Muhammad Al Yafi',
          parents: 'Putra dari Bapak Rizal & Ibu Mariana',
          image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format',
        },
        bride: {
          name: 'Yova Rahmadani',
          parents: 'Putri dari Bapak Hendra & Ibu Sari',
          image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format',
        },
      },
      elements: [],
      widgets: [],
      editableProperties: ['groom.name', 'groom.parents', 'groom.image', 'bride.name', 'bride.parents', 'bride.image'],
    },
    {
      id: 'event',
      type: 'event',
      title: 'Acara',
      enabled: true,
      config: {
        events: [
          {
            name: 'Akad Nikah',
            date: 'Minggu, 10 Jan 2027',
            time: '08:00 - 10:00 WIB',
            venue: 'Kediaman Mempelai Wanita',
            address: 'Jl. Merdeka No. 12, Lhokseumawe',
          },
          {
            name: 'Resepsi',
            date: 'Minggu, 10 Jan 2027',
            time: '11:00 - 15:00 WIB',
            venue: 'Gedung Serbaguna Anggun',
            address: 'Jl. Malikussaleh No. 5, Lhokseumawe',
          },
        ],
      },
      elements: [],
      widgets: [
        { id: 'maps-akad', type: 'maps', config: { lat: 5.180, lng: 97.150 } },
      ],
      editableProperties: ['events'],
    },
    {
      id: 'story',
      type: 'story',
      title: 'Kisah Cinta',
      enabled: true,
      config: {
        stories: [
          { date: '2019', title: 'Pertama Bertemu', content: 'Dipertemukan di bangku kuliah yang sama, awal dari cerita panjang kami.' },
          { date: '2023', title: 'Melamar', content: 'Di bawah senja, sebuah janji sederhana diucapkan untuk melangkah bersama.' },
          { date: '2027', title: 'Menikah', content: 'Hari yang telah kami nantikan, saatnya menyatukan dua keluarga.' },
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['stories'],
    },
    {
      id: 'gallery',
      type: 'gallery',
      title: 'Galeri',
      enabled: true,
      config: {
        images: [
          'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format',
          'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&auto=format',
          'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&auto=format',
          'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&auto=format',
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['images'],
    },
    {
      id: 'rsvp',
      type: 'rsvp',
      title: 'RSVP',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
    {
      id: 'wishes',
      type: 'wishes',
      title: 'Ucapan',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
  ],
}
