import { InvitationTemplate } from '../types'

export const moonlight_garden_v1: InvitationTemplate = {
  id: 'moonlight-garden',
  name: 'Moonlight Garden',
  slug: 'moonlight-garden',
  category: 'Floral',
  style: '3D Parallax Floral',
  thumbnail: 'photo-1519741497674-611481863552',
  version: '1.0',
  status: 'published',
  price: 150000,
  badge: '3D Parallax',
  description: 'Cinematic garden experience with multi-layer depth and floating petals.',
  keyFeatures: ['Multi-Layer Parallax Depth', 'Floating Petal Animation', 'Cinematic Cover', 'RSVP & Guestbook'],
  experience: 'Layered floral illustrations move at different depths as guests scroll, while soft petals drift across the screen \u2014 a cinematic, garden-at-night feeling designed to impress on mobile.',
  theme: {
    colors: {
      primary: '#2E3A59',
      secondary: '#8FA998',
      accent: '#C9A9E3',
      background: '#F4F1FA',
      text: '#2A2438',
      card: '#FFFFFF',
    },
    fonts: {
      heading: 'Cormorant Garamond',
      body: 'Jost',
    },
    borderRadius: '9999px',
  },
  animations: [
    { type: 'petal-float', duration: 8000, delay: 0, repeat: true },
    { type: 'soft-parallax', duration: 1200, delay: 0 },
  ],
  sections: [
    {
      id: 'cover',
      type: 'cover',
      title: 'Cover',
      enabled: true,
      config: {
        groomName: 'Al Yafi',
        brideName: 'Yova',
        date: '10 Januari 2027',
        backgroundImage: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200&auto=format',
      },
      elements: [],
      widgets: [],
      animation: { type: 'petal-float', duration: 8000, delay: 0, repeat: true },
      editableProperties: ['groomName', 'brideName', 'date', 'backgroundImage'],
    },
    {
      id: 'couple',
      type: 'couple',
      title: 'Mempelai',
      enabled: true,
      config: {
        groom: {
          name: 'Muhammad Al Yafi',
          parents: 'Putra dari Bapak Rizal & Ibu Mariana',
          image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format',
        },
        bride: {
          name: 'Yova Rahmadani',
          parents: 'Putri dari Bapak Hendra & Ibu Sari',
          image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format',
        },
      },
      elements: [],
      widgets: [],
      editableProperties: ['groom.name', 'groom.parents', 'groom.image', 'bride.name', 'bride.parents', 'bride.image'],
    },
    {
      id: 'event',
      type: 'event',
      title: 'Acara',
      enabled: true,
      config: {
        events: [
          {
            name: 'Akad Nikah',
            date: 'Minggu, 10 Jan 2027',
            time: '08:00 - 10:00 WIB',
            venue: 'Taman Bunga Cattleya',
            address: 'Jl. Kebun Raya No. 3, Medan',
          },
          {
            name: 'Resepsi',
            date: 'Minggu, 10 Jan 2027',
            time: '18:00 - 21:00 WIB',
            venue: 'The Garden Hall',
            address: 'Jl. Sisingamangaraja No. 8, Medan',
          },
        ],
      },
      elements: [],
      widgets: [
        { id: 'maps-akad', type: 'maps', config: { lat: 3.595, lng: 98.672 } },
      ],
      editableProperties: ['events'],
    },
    {
      id: 'story',
      type: 'story',
      title: 'Kisah Cinta',
      enabled: true,
      config: {
        stories: [
          { date: '2021', title: 'Bertemu di Taman', content: 'Sebuah pertemuan tak terduga di antara rimbunnya bunga cattleya.' },
          { date: '2024', title: 'Bulan Purnama', content: 'Di bawah cahaya bulan, ia berlutut dan mengucap janji setia.' },
          { date: '2027', title: 'Malam Pernikahan', content: 'Taman yang sama menjadi saksi janji suci kami berdua.' },
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['stories'],
    },
    {
      id: 'gallery',
      type: 'gallery',
      title: 'Galeri',
      enabled: true,
      config: {
        images: [
          'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&auto=format',
          'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&auto=format',
          'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format',
          'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&auto=format',
        ],
      },
      elements: [],
      widgets: [],
      editableProperties: ['images'],
    },
    {
      id: 'rsvp',
      type: 'rsvp',
      title: 'RSVP',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
    {
      id: 'wishes',
      type: 'wishes',
      title: 'Ucapan',
      enabled: true,
      config: {},
      elements: [],
      widgets: [],
      editableProperties: [],
    },
  ],
}
